### ISSUE TITLE
Install instructions don't work

### ISSUE THREAD

**Issue by crobbo** [Nroulston/form_for_materialize#2]
`ERROR:  Could not find a valid gem 'form_for_materialize' (>= 0) in any repository`

Getting the above error.

**Comment by Nroulston** [comment]
Hi @crobbo, I had completely forgotten to update the Readme on this project. It was something that I was working on while looking for a job, and haven't needed to use Materialize at the place of my work. If you want to use this as a base go ahead and copy and paste, or clone it. The form builder is the key component here and is a good starting point for modifying the rest of the form tags that you might want to use with Materialize.
